api:
  insecure: false
  dashboard: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "jadus-network"

tls:
  certificates:
    - certFile: "/certs/api.pem"
      keyFile: "/certs/api-key.pem"

log:
  level: INFO


